"""empty message

Revision ID: 0a9e1bfe00a6
Revises: bf85936c27d0
Create Date: 2022-01-14 19:59:29.083294

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '0a9e1bfe00a6'
down_revision = 'bf85936c27d0'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('player', sa.Column('public_id', sa.String(length=50), nullable=True))
    op.add_column('player', sa.Column('password', sa.String(length=80), nullable=True))
    op.create_unique_constraint(None, 'player', ['public_id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'player', type_='unique')
    op.drop_column('player', 'password')
    op.drop_column('player', 'public_id')
    # ### end Alembic commands ###
