"""empty message

Revision ID: bf85936c27d0
Revises: 
Create Date: 2021-12-19 21:15:19.549564

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'bf85936c27d0'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('paperwork', sa.Column('document_type', sa.String(), nullable=False))
    op.drop_column('paperwork', 'file_type')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('paperwork', sa.Column('file_type', sa.VARCHAR(), autoincrement=False, nullable=False))
    op.drop_column('paperwork', 'document_type')
    # ### end Alembic commands ###
